### ISSUE TITLE
added link conatins `%2F`, results in download failure

### ISSUE THREAD

**Issue by topic2k** [seansfkelley/synology-download-manager#102]
### Versions

**Extension version**: 0.5.6

**Browser and version**: Firefox 65.0.2

**DSM version**: DSM 6.2.1-23824 Update 6

**Download Station version**: 3.8.12-3518

### Steps to Reproduce the Issue

1. goto [example page](https://ci.appveyor.com/project/EventGhost/eventghost/builds/22782703/artifacts).
2. inspect the link for [_build\output\EventGhost_WIP-2019.03.03-12.37.55_Setup.exe](https://ci.appveyor.com/api/buildjobs/hq8bnr676w38a9tp/artifacts/_build%2Foutput%2FEventGhost_WIP-2019.03.03-12.37.55_Setup.exe).
3. the href contains `%2F` which needs to be converted to `/` before adding to DownloadStation.

**Comment by seansfkelley** [comment]
I _think_ this is a bug on Synology's part, but it's confounded by AppVeyor having very lenient URL policies.

AppVeyor seems to serve the file at both URLs, as both of the following commands work.

```sh
wget 'https://ci.appveyor.com/api/buildjobs/hq8bnr676w38a9tp/artifacts/_build%2Foutput%2FEventGhost_WIP-2019.03.03-12.37.55_Setup.exe'

# ... snip

2019-03-09 09:29:57 (8.95 MB/s) - ‘_build%2Foutput%2FEventGhost_WIP-2019.03.03-12.37.55_Setup.exe’ saved [19075298/19075298]
```

```sh
wget 'https://ci.appveyor.com/api/buildjobs/hq8bnr676w38a9tp/artifacts/_build/output/EventGhost_WIP-2019.03.03-12.37.55_Setup.exe'

# ... snip

2019-03-09 09:30:08 (8.74 MB/s) - ‘EventGhost_WIP-2019.03.03-12.37.55_Setup.exe’ saved [19075298/19075298]
```

This means that in this particular case, it is okay to decode the URL.

However, in the general case, I don't think it is -- the URL with `%2F` is referring to a different path than the URL-decoded one, as can be seen in the outputs of `wget` stating that the downloaded file has two different names. That they are the same file is, I'm pretty sure, a feature of AppVeyor and not necessarily always the case.

It is likely that for most sites, decoding the URL will result in a different URL that doesn't actually exist, because most sites probably do not transparently equate '%2F` and `/` in the names of files.

So, unfortunately, I don't think I can make a change here without potentially breaking other sites.

**Comment by topic2k** [comment]
Ok, thank you for looking at it and the explanation.
