### ISSUE TITLE
Connection not recovered on download

### ISSUE THREAD

**Issue by SpiReCZ** [seansfkelley/synology-download-manager#111]
If the connection is lost you can now recover it with "Test Connection" button.

But if your try directly download something it will fail on unable to connect and the connection is not recovered automatically.

### Versions

**Extension version**: 0.5.8

**Browser and version**: Firefox 68.0.1

### Steps to Reproduce the Issue

1. Be on network without access to the NAS
2. Turn on browser.
3. Switch to network with ability to connect to the NAS
4. Try download something
5. Fails on unable to connect.

It should try to recover the connection once. Something like with the Test Connection button.

**Comment by seansfkelley** [comment]
Hm, it's definitely supposed to try to recover in this way, so it's a bug that it doesn't. Thanks for the detailed report; I'll try to take a look at this within the week!

**Comment by seansfkelley** [comment]
Hey @SpiReCZ, I tried to fix this but I wasn't able to reproduce the issue.

Can you let me know if you still experience this issue? I made some changes to the way that the extension talks over the network, so I may have inadvertently fixed it. Check out the new version, 0.6.0.

**Comment by SpiReCZ** [comment]
I can confirm that the new version produces the same issue..

I reproduced the issue by:

1. turning off internet connection (wifi).
2. started firefox with 0.60 plugin.
3. clicked on the plugin icon in the plugin bar
4. plugin started refreshing the list of tasks and failed to connect
5: i turned on internet connection
6. clicked on magnet link on some website
7. plugin responded with 2 notifications: (adding torrent, failed to connect)

---

Only thing that helped to recover connection was:
1. go to plugin settings
2. click `Test Connection and Save`
3. connection was successful

Also the localization of some texts is now in Cyrillic: `Updated несколько секунд назад`

**Comment by seansfkelley** [comment]
Ah, got it! I'm able to reproduce the issue; thank you very much for the detailed steps.

Regarding the localization issue, someone else has filed the same issue. I'm trying to chase down why that happens because I'm not able to reproduce it yet. If you're willing to help, following [these steps](https://github.com/seansfkelley/synology-download-manager/issues/124#issuecomment-537752552) and reporting your results would be very useful!

**Comment by seansfkelley** [comment]
Note to self: took another look at this. The error is caused by the usage of `ApiClient` from synology-typescript-api. It holds onto connection failures during login indefinitely:

https://github.com/seansfkelley/synology-typescript-api/blob/1f54b7fcd3301542f40e9ca634f86d9520f63437/src/client.ts#L247-L248

So what's happening during the provided repro is that the extension starts without an internet connection and fails to login. That puts `ApiClient` permanently into a bad state. "Test Connection and Save" is a workaround because it forcibly logs out the current session and tries again.

A shortcut repro I tried was to have the extension in a working state, turn off the internet, then try to load tasks. This doesn't repro the issue because the login request that the client is holding onto is still good -- it was cached while the internet was enabled -- but the data requests are failing. Failed data requests will retry, and sometimes even attempt a logout:

https://github.com/seansfkelley/synology-typescript-api/blob/1f54b7fcd3301542f40e9ca634f86d9520f63437/src/client.ts#L252-L260

So this issue only happens when the login request itself hits an error, and _I think_ that only happens if the extension starts up while the internet is disabled or otherwise is likely to hit a connection error. Even "Test Connection and Save" can't get you into this state, because it won't allow you to start a new session if it can't reach the NAS at the time you hit the button.

Options:

- synology-download-manager can do logout-and-retry-once on connection failures
- synology-typescript-api can change when it decides to transparently retry a connection failure during login
