### ISSUE TITLE
Youtube: Is it possible to pull the name of the file, instead of `_.mp4`?

### ISSUE THREAD

**Issue by christopher-wilson** [seansfkelley/synology-download-manager#112]
I'm not sure if this is a feature request or a bug report. Currently, downloading Youtube videos only creates files with the name `_.mp4` or some variation of that. Is it possible to bring in the video title as the filename?

I've tried this on both Chrome and Firefox, same result each time, so it may be an issue with the Download Station itself?

**Comment by seansfkelley** [comment]
Yeah, I think this is a limitation of the way the Synology works, because:

- there's no way in the documented API to assign a name to a download
- there's no way in the Download Station UI to assign a name to a download
- during the course of the download the name changes from things like `watch?v=34893uo53` to `_.mp4`, which suggests that the NAS is trying to figure out a name on its own

I don't think there's any way at all to do this, even through the official UI. Sorry!
