### ISSUE TITLE
does not work anymore ?

### ISSUE THREAD

**Issue by tparvais** [seansfkelley/synology-download-manager#113]
Thanks for filing an issue! I appreciate you taking the time to help improve Synology Download Manager.

### Versions
0.5.8

**Browser and version**: (usually found in the browser's "About")

Firefox 68.0.1 (64 bits)

**DSM version**: (DSM > Control Panel > Info Center > General > DSM version)

Syno DS916+
DSM 6.2.2-24922 Update 2 

**Download Station version**: (DSM > Package Center > Installed > Download Station > Installed version)

### Failure Logs

Redacted extension state: {
  "connection": {
    "protocol": "https",
    "hostname": true,
    "port": true,
    "username": true,
    "password": true
  },
  "visibleTasks": {
    "downloading": true,
    "uploading": true,
    "completed": true,
    "errored": true,
    "other": true
  },
  "taskSortType": "name-asc",
  "notifications": {
    "enableFeedbackNotifications": true,
    "enableCompletionNotifications": false,
    "completionPollingInterval": 60
  },
  "shouldHandleDownloadLinks": true,
  "tasks": 3,
  "taskFetchFailureReason": null,
  "tasksLastInitiatedFetchTimestamp": 1564557114931,
  "tasksLastCompletedFetchTimestamp": 1564557116003,
  "lastSevereError": "(omitted for brevity)",
  "stateVersion": 3
}

Error: 'Network Error'
Error stack trace: createError@moz-extension://fab0b645-12ed-4645-92be-67f3b6b7f567/dist/js/background.js:2871:15
handleError@moz-extension://fab0b645-12ed-4645-92be-67f3b6b7f567/dist/js/background.js:3185:14

### Steps to Reproduce the Issue

When I send a torrent to extension, it does not work and display "unexpected error, please check your settings.
I checked them and they are ok
If I copy-paste the torrent directly to DS Download, it works

**Comment by seansfkelley** [comment]
Network errors are usually transient or caused by inaccessible URLs. Some questions to help me debug:

- Are you using a private tracker, or otherwise using a site that the Synology (not your browser) might not be able to access?
- Is it a magnet link, or a link to a .torrent file?
- Did this site used to work through the extension?
- Do other sites/downloads work still work?
- What do you mean when you say it works if you copy-paste the torrent directly into DS Download? Are you pasting in the URL or uploading a .torrent file?
- Did you try using "Test Connection" to force it to reset its login?

For my own records, this would be helped by #95.

**Comment by seansfkelley** [comment]
Closing due to lack of response; current report is not actionable.
