### ISSUE TITLE
[Bug] Links with a comma in their url are cut-off and return an "unkown error" popup

### ISSUE THREAD

**Issue by Zaturi** [seansfkelley/synology-download-manager#118]
### Versions

**Extension version**: 0.5.8

**Browser and version**: Firefox 68.0.1

**DSM version**: DSM 6.2.2-24922 Update 2

**Download Station version**: 3.8.14-3543

### Steps to Reproduce the Issue

1. Right click on a link that contains a comma
2. Select "Download with DownloadStation" action
3. Only the part of the link up to the comma is added to the Download Station and an "unknown error" popup appears

Note: The same error happens when trying to add a link containing a comma via the "Add download..." action of the extension. The link itself can be manually added to the Download Station without problem.

PS: Thank you for your hard work, I really like this extension a lot!

**Comment by seansfkelley** [comment]
Thanks for the detailed report! I spent a while digging around trying to find the right solution, but I think that's too complicated for me to test safely.

However, a cheap solution that might solve most or all cases in the real world is to string-replace `,` with `%2C`. This is specifically _not_ a full URL encoding. This is a hack that takes advantage of the fact that (1) commas are never significant to delineate the important bits of a URL, like the protocol or query string and (2) commas are very important to the Synology and their presence un-encoded is certainly incorrect as it will cause the Synology to erroneously split the URL.

I'll have to try this out on my Synology to see if it actually helps. I'm surprised you said it works through the Download Station UI directly -- in my tests, it was behaving the same as the extension with commas in URLs.

### Details, and also for my future self

The basic problem is one of encoding. In Firefox if you right-click-copy-location on, say, a magnet link with a comma in it, you'll get something like `magnet?:dn=foo%2Cbar`, assuming the site is well-behaved with how it's encoding its URLs. `%2C` is the URL-encoded version of `,`, but what's important to note here is that only part of this string is URL encoded, because the string itself is a URL. When we put it in the request to the Synology, it gets URL encoded _again_, so some **but not all** things will be URL encoded twice.

In the general case you can't just blindly URL encode or decode the URL string, because (1) if it's already URL encoded and you do it again, it'll happen a third time when you send it over the wire, at which point it's _too_ encoded to parse properly and (2) if you decode it first in an attempt to "normalize" all encodings away, you lose the distinction between elements that have been URL encoded once and zero times, so when you re-encode it, it ends up as an invalid URL because too many things are encoded. Using `encodeURI` instead of `encodeURIComponent` doesn't get around this, because the former doesn't encode enough (i.e. commas) and the latter too much (i.e. colons).

I think the true solution is a pretty involved URL parsing dance where you attempt to parse the string as a URL into its constituent parts, then figure out which parts you should decode/re-encode to get them encoded exactly once, then re-assemble the URL and ship it off. Unfortunately, I have very few test cases to attempt this on so I'm very wary of such a tricky scheme actually working in practice. Who knows what kind of weird URL schemes are out there that Just Work because the site maintainers and the browsers are cooperating to present a properly URL-encoded string to the Synology?
