### ISSUE TITLE
Cannot download proper torrent file on firefox extension

### ISSUE THREAD

**Issue by htudor** [seansfkelley/synology-download-manager#146]
In Firefox extension if a private torrent site doesn't have the link with the .torrent file (eg : https://website.com/download.php?id=697563 ) it will not add the torrent file, but instead it will download a file called login.php
The chrome extension works fine downloading the correct torrent file.
Also can you please add the advanced menu for the download like on chrome.

**Comment by seansfkelley** [comment]
Unfortunately, not all private trackers are supported. The extension will try to figure out if a link you download is actually a link to a .torrent, but if the site is not well-behaved it might not report the necessary information for the extension to determine that.\* In that case, the extension defaults to downloading whatever page is being linked to because it can't do anything else.

Does the extension work on other private trackers? That could help confirm/deny that it's the site in question that is not cooperating.

Which Chrome extension are you referring to? This extension is [Synology Download Manager](https://chrome.google.com/webstore/detail/synology-download-manager/iaijiochiiocodhamehbpmdlobhgghgi) but it sounds like you're referring to [Synology Download Station](https://chrome.google.com/webstore/detail/synology-download-station/onhbegdkgonhlokobjefolhpoidcnida), which is unaffiliated with this project. I'm surprised it would behave differently -- both these extensions use a similar algorithm to forward .torrent files to the NAS. Can you provide any more detail about that?

I'm not sure what you mean by:

> advanced menu for the download like on chrome

Are you asking for the same thing as https://github.com/seansfkelley/synology-download-manager/issues/128 or https://github.com/seansfkelley/synology-download-manager/issues/50?

\* Synology Download Manager will make a HEAD request, and if the site reports a known `Content-Type` header or has a known extension, it will attempt to download the .torrent file and forward it to the NAS. I know of a couple sites that don't respond to HEAD requests, which breaks this feature. The NAS itself is unable to fetch the file, because it's not logged into the tracker like your browser is. Synology Download Manager will also fail to forward the .torrent if the HEAD request states that it's larger than 5MB.

**Comment by seansfkelley** [comment]
Ping @htudor can you provide any more detail?
