### ISSUE TITLE
Failed to connect to diskstation

### ISSUE THREAD

**Issue by Esofasto** [seansfkelley/synology-download-manager#148]
### Description

"Failed to connect to diskstation please check your settings" error when clicking a torrent/  magnet link. **Diskstation is connected in DLM settings**  

### Steps to Reproduce the Issue

Just try to click a download link (every time)

### Failure Logs

No Log

### Versions

**Extension version**: 
0.7.0

**Browser version**: (usually found in the browser's "About")

77.0.1

**DSM version**: 

6.2.3-25426

**Comment by seansfkelley** [comment]
Given that you had to do some configuration juggling in #147, have you tried (1) doing "test connection and save" or (2) removing and re-adding the extension? It's possible you've hit a legit issue here in that the extension has gotten into a weird state due to your previous connection failures. "Test connection and save" will try to drop the existing connection and establish a new one, so it might fix the issue.

If neither of those options work, then there's something more complex to debug here. I've also been working on and off on improving the connection management but I haven't released those changes yet.

**Comment by seansfkelley** [comment]
@Esofasto is this still an issue?

**Comment by Esofasto** [comment]
No the issue has gone, however I am uncertain as to how. I think it went after I turned the NAS off. It was off for a couple of days and when turned it back on the issue had disappeared, must of been a cache problem of some sort. Thanks for looking into it.

**Comment by seansfkelley** [comment]
Okay, thanks for following up! Looks like there were a handful of transient issues that came up around the same time so I suspect Firefox changed something internally that required a reset of sorts.
