### ISSUE TITLE
Any way to capture K2S downloads (You can't use right click menu)

### ISSUE THREAD

**Issue by Musicalfidelity** [seansfkelley/synology-download-manager#163]
Would like to use Firefox and directly download files from K2S to NAS, in the same way as magnets etc. You can't just right click.

Many thanks in advance for consideration.

**Comment by seansfkelley** [comment]
I'm not familiar with K2S, but as you are the third person in recent days to ask a similar question, I've just added [an answer on this topic](https://github.com/seansfkelley/synology-download-manager/blob/master/FAQ.md#why-cant-i-start-a-download-from-a-site-or-how-do-i-start-a-download-with-a-site) to the FAQ which I believe explains (but does not resolve) your issue.

Unfortunately, I can't think of anything more that Synology Download Manager can do that it doesn't already in order to work with sites that have unusual download behavior. For that reason I'm going to close this issue, but if you can demonstrate that this is actually a bug or is otherwise feasible to fix on my part, please comment and I can take a look.
