### ISSUE TITLE
Magnet association with NAS Download Manager

### ISSUE THREAD

**Issue by Francois59870** [seansfkelley/synology-download-manager#237]
bonjour,
j'utilise cette extension sur firefox depuis longtemps et elle me convient très bien ;
enfin, jusqu'à hier !
je ne sais pas pourquoi, lorsque maintenant je clique sur un fichier .magnet, firefox me demande avec quelle application je désire ouvrir ce fichier ;
j'ai bien essayé d'entrer le chemin de Firefox.exe, mais il ne se passe rien ;
j'ai désinstallé et ré-installé l'extension NAS Download Manager, toujours pareil ;
est-ce un problème de Firefox, de l'extension, autre ?
merci d'avance de vos bons conseils

**Comment by seansfkelley** [comment]
The auto-downloading behavior for magnet links is not terribly reliable, unfortunately. Did it used to work on the specific site you're using?

A lot of things need to be true at the same time for it to work (it needs to be enabled, you need to left-click it, and it needs to be an `<a>` element with an `href` attribute using the `magnet` protocol), since there's no browser-supported way for extensions to handle opening links:

https://github.com/seansfkelley/nas-download-manager/blob/e2a0c8ea1f3b71a9018cb30028e428f6c4f5033c/src/content/index.ts#L31-L43

When it's working, you shouldn't get that popup asking at all. Make sure the setting is enabled (English name: "handle opening downloadable link types"). I don't think anything has changed in Firefox, so I would guess something changed about the site you're using. You can also check in Chrome to see if it works there.

**Comment by Francois59870** [comment]
Hi !
thanks for answer ;
my problem is resolved, I don't know how it is, but ... it works !
maybe as you said something wrong on the site witch provides the magnet
files ...
thanks again Sean !

Le lun. 12 févr. 2024 à 20:26, Sean Kelley ***@***.***> a
écrit :

**Comment by seansfkelley** [comment]
Glad to hear it!
