### ISSUE TITLE
**bug report** not working with www.newpct1.com "download" button

### ISSUE THREAD

**Issue by jualbacar** [seansfkelley/synology-download-manager#55]
Browser and version: Firefox QUANTUMM 57.0.1
DSM version: 6.1.4-15217-2
Download Station version: 3.8.7-3490

Steps to Reproduce the Issue

1. Go to www.newpct1.com
2. choose a download
3. open context-menu and click "download with download station"
4. Link to be opened always is "javascript:void(0);"
5. no redirection to download link, so not working.

thanks for the job

**Comment by seansfkelley** [comment]
Unfortunately there's not a great way to get at links that are hidden behind a javascript snippet.

Ideally, Synology Download Manager could be registered as a handler for the generic browser-wide "what do you want to do with this download" popup, which is tracked by #45.

Since (as of this writing) that doesn't appear to be possible, the best I can offer is a workaround: after you've downloaded the .torrent, you can open the Downloads view in your browser and get the URL and paste that into Synology Download Manager. Sorry there isn't a better solution!
