### ISSUE TITLE
Issues Creating tasks and no "advanced download option"

### ISSUE THREAD

**Issue by Alfr3eD** [seansfkelley/synology-download-manager#56]
### Versions

**Extension version**: (visible in Synology Download Manager's settings (Firefox) or in the extension list (Chrome))
0.4.1

**Browser and version**: (usually found in the browser's "About")
Mozilla Firefox 57.0.2 (64-bit)

**DSM version**: (DSM > Control Panel > Info Center > General > DSM version)
DSM 6.1.4-15217 Update 1

**Download Station version**: (DSM > Package Center > Installed > Download Station > Installed version)
3.8.7-3490

### Steps to Reproduce the Issue

1. Can't add the tasks at all, works in Chrome though,

**Comment by seansfkelley** [comment]
Can you be more specific? How are you trying to add tasks?

The title sounds like it also includes a feature request; if that's the case, what would you expect to see in an "advanced download" form?

**Comment by Alfr3eD** [comment]
When even I add a donwload task with Chrome I get the the option to choose where to save the file and it works,
https://img42.com/Y94HP+

But in FIrefox I only get,
https://img42.com/Sz4MD

When I first add it,
https://img42.com/ElRo9

Then I get the following error all the time,
https://img42.com/2lvrX

As mentioned, works in Chrome.

**Comment by seansfkelley** [comment]
The screenshot you showed of Chrome is a different extension which does not have a Firefox version, which is why you're seeing different behaviors.

I don't plan to implement similar functionality for right-click-advanced-add (#13) to that that you're using in the Chrome extension.

The "torrent invalid" error is detected by the DiskStation, and Synology Download Manager can't do much except show you that error. If it's not immediately obvious why the torrent is considered broken, you might have to open DSM itself for more details or try the same file in other torrent clients to see if they give you a more descriptive reason for the failure.

I believe this answers all your questions, so I'm going to close this issue out.
