### ISSUE TITLE
Hogging up CPU to 100%

### ISSUE THREAD

**Issue by cypresstwist** [seansfkelley/synology-download-manager#70]
I really like this extension. I realy do. But for the past two weeks my CPU has been going crazy and I could not figure out why. When I finally narrowed it down to this extension I thought of cryptocurrency mining and left a review stating my suspicion. I might have been wrong, as the developer assured me this extension is not mining cryptocurrency so I deleted the review. This still leaves me with the cpu hogging issue which was not present before January the 5th.

> Maintainer edit: replaced the original content with the content from the AMO review.

**Comment by seansfkelley** [comment]
Thanks for updating your review, and I'm sorry that this extension might be causing CPU issues

Are you sure that this extension is at fault? If you start a new Firefox profile and install/configure only this extension, does it still spike your CPU? Another thing you can try is deleting (not just disabling) the extension, then re-installing it. This will clear the cache and your credentials (so you'll have to re-login), but it's conceivable that you somehow got into some crazy state on the 5th that might be circumvented by starting afresh.

I haven't released any new versions since 2017-11-19 (0.4.1), so I'd be surprised if you were a month and a half late to the upgrade train and 0.4.1 is at fault. More likely it's a latent bug and something else changed on 2018-01-05 to trigger it.

**Comment by cypresstwist** [comment]
Sorry to have written that review in the first place.
I did as you said - reinstalled. I'll test it again in the next 24 hours and see if the issue comes up again. I'll keep you updated.

**Comment by seansfkelley** [comment]
Are you still seeing CPU issues after reinstalling the extension?

**Comment by cypresstwist** [comment]
No - the problem went away after I reinstalled.

**Comment by seansfkelley** [comment]
Hmm, very mysterious. I'm going to close this out, but if it comes back let me know.
