### ISSUE TITLE
Simple not working for certain sites

### ISSUE THREAD

**Issue by TomAce79** [seansfkelley/synology-download-manager#72]
### Versions
**Extension version**: Synology Download Manager
**Browser and version**: Firefox 58.0.2 64 bit
**DSM version**: (DSM > Control Panel > Info Center > General > DSM version)
**Download Station version**: 3.8.7-3490

### Steps to Reproduce the Issue
1. Right click => Download with DownloadStation
2. Bottom right window Torrent added pops up
3. Top right torrent invalid
Otherwise works perfectly with Download station itself. I've tried with another site there it is working.

### The issue here I guess:
When I add the torrent with your number the torrent is added to the Download station as the following:
[bHUm_#482145]File_name.torrent
When I add it manually it is added:
File_name

I hope you can do something with it because it would be a great program.

**Comment by seansfkelley** [comment]
The issue is likely that the site is either not responding or is responding in an unexpected manner when we ask it what file type the URL is referring to. Without the URL I can't verify this, but if you'd like to help you can do the following:

1. Navigate to the page where you have the torrent.
2. Open a new tab, go to `about:debugging` and "Enable add-on debugging".
3. Still in `about:debugging`, find Synology Download Manager and hit "Debug". This will open a new copy of Firefox for debugging extensions, and the warning is safe to accept.
4. In the debugging window you just opened, switch to the "Network" tab (along the top of the window) and clear any existing requests (trash can button on the top left).
5. Back at the page with the torrent, right-click the link and add the download task.
6. In the debugging window, you should see a line item whose "Method" (second column by default) is listed as `HEAD`. Right-click that > Copy submenu > Copy response headers, and paste those contents here (after redacting any credentials, etc.).

Thanks!

**Comment by khrt** [comment]
Most probably related to #73

**Comment by seansfkelley** [comment]
@TomAce79 can you try out the newest version as of today (v0.5.1) and see if it fixes your issue?

**Comment by seansfkelley** [comment]
Closing due to likely similarity to #73 and lack of response.
