### ISSUE TITLE
addon not showing at all

### ISSUE THREAD

**Issue by synthetical** [seansfkelley/synology-download-manager#83]
using the latest firefox, plugin won't show the settings menu when i click the icon, just a blank box.

**Comment by seansfkelley** [comment]
What version of Firefox and the extension are you using? Are you able to get to the Preferences page of the addon (through `about:addons`)? The latest version may show a "debugging" section at the bottom that would be useful to include the contents of here.

**Comment by synthetical** [comment]
Firefox 59.0.2, addon is installed and listed. Tried to install and delete multiple times.

**Comment by seansfkelley** [comment]
Can you go to `about:addons` and open the Preferences page? If that works, there may be a section at the bottom labelled "Debugging" that will have useful debugging information.

![pasted_image_3_31_18__12_28](https://user-images.githubusercontent.com/2101409/38166814-323d0542-34df-11e8-929a-923aba74f8ec.png)

**Comment by synthetical** [comment]
theres an options button, but if i go there theres nothing i can do besides the "standard stuff" like see the features, set automatic updates and enable/disable.

**Comment by seansfkelley** [comment]
Hm, I've never seen a failure like that before, and the mechanisms I added to help me debug it easily are no use. If you want to dig a little more to help me debug this particular issue, you may be able to find some useful logging following these steps:

1. Open a new tab, go to `about:debugging` and "Enable add-on debugging" (near the top).
2. Find Synology Download Manager in the list and hit "Debug" on it, which will open a new debugging Firefox window (you'll have to accept a warning).
3. Switch to the Console tab in that window (along the top), and if it's got stuff in it I suggest you clear it (trash can icon on the top left) because it accumulates logging from every open tab (for some reason).
4. Open Synology Download Manager's Preferences page (or reload it, if you already have it open).
5. If any logs appear in the Console, include them here.

Thanks!

**Comment by synthetical** [comment]
clicking on the plugin icon
```
(poll-1) polling for tasks...  popup.js:28423:5
(poll-1) poll completed with response Object { type: "missing-config" }  popup.js:28437:9
TypeError: settings is undefined[Learn More] popup.js:28170:1
```
if i click on options i get so many lines and it wont stop creating new ones, the window freezes every few seconds -> https://i.imgur.com/3XY2ykT.png

**Comment by seansfkelley** [comment]
Alright, this is a little more involved than I first thought so unfortunately I can't do it right now. However, you can gather one more piece of information that would be very helpful. In the same Console page, at the bottom in the text area, paste the following and hit enter, then copy-paste the output it gives you on this ticket.

```js
function redactState(state) {
    const sanitizedConnection = state.connection
	    ? Object.assign(
	    	{}, 
	    	...Object.keys(state.connection).map(k => ({ [k]: !!state.connection[k] })), 
	    	{ protocol: state.connection.protocol }
		)
		: '(nothing!)';
    return Object.assign(
    	{}, 
    	state, 
    	{ lastSevereError: state.lastSevereError ? '(omitted for brevity)' : undefined, connection: sanitizedConnection, tasks: (state.tasks ? state.tasks.length : '(nothing!)') }
	);
};

browser.storage.local.get(null).then(x => console.log(JSON.stringify(redactState(x), null, 2)));
```

It shows a redacted version of the state of the extension so I can debug further. You should double-check the output to make sure no passwords or such are listed, but you should get something more or less like this:

```json
{
  "tasks": 0,
  "taskFetchFailureReason": null,
  "tasksLastCompletedFetchTimestamp": 1522534008428,
  "tasksLastInitiatedFetchTimestamp": 1522534062386,
  "cachedTasksVersion": 1,
  "connection": {
    "protocol": "https",
    "hostname": true,
    "port": true,
    "username": true,
    "password": true
  },
  "visibleTasks": {
    "downloading": true,
    "uploading": true,
    "completed": true,
    "errored": true,
    "other": true
  },
  "taskSortType": "name-asc",
  "notifications": {
    "enableFeedbackNotifications": true,
    "enableCompletionNotifications": false,
    "completionPollingInterval": 60
  },
  "shouldHandleDownloadLinks": true,
  "stateVersion": 3
}
```

Notes to future self:
- `popup.js:28170` is the definition of `getHostUrl`, which in the popup would only be called from the callback inside `onStoredStateChange`; i.e., it implies that the state doesn't have the proper keys.
- `settings.js:24443` is where `rawPollingInterval` is initialized in `SettingsForm`, again implying that the extension state is missing keys we need.

**Comment by synthetical** [comment]
Promise { <state>: "pending" }
{
  "tasks": 0,
  "taskFetchFailureReason": "missing-config",
  "tasksLastCompletedFetchTimestamp": 1522531561402,
  "tasksLastInitiatedFetchTimestamp": 1522531561396,
  "cachedTasksVersion": 1,
  "lastSevereError": "(omitted for brevity)",
  "connection": "(nothing!)"
}

**Comment by seansfkelley** [comment]
I just published version 0.5.4 which should fix this issue. Please try it out and let me know!

**Comment by synthetical** [comment]
@seansfkelley thanks for the help and your awesome plugin!

**Comment by synthetical** [comment]
minor issue: the checkboxes under 'task display settings' in about:addons cant be clicked

**Comment by seansfkelley** [comment]
Just pushed another update for the checkboxes issue.

As for the connection failure, that message only comes up when the addon is fairly confident that the issue is one of those three causes. Usually, it ends up being a certificate issue: are you able to log in to DSM directly using the same hostname/port/username/password combination on the same browser without any certificate warnings? I had to add a permanent exception to Firefox for my self-signed cert for the addon to work.
