### ISSUE TITLE
2-Step Verification

### ISSUE THREAD

**Issue by 3ventHori7on** [seansfkelley/synology-download-manager#88]
First - thanks for the nice add-on.

I have successfully set up synology download manager in Firefox on a number of computers with no problem. On my Mac I am getting a message saying 2-step verification is required and it won't allow me to connect to my NAS. I have tried disabling 2-step verification on my NAS but it doesn't seem to work. Furthermore, I don't understand why I could set it up on a PC without the 2-step verificaiton problem but not on my Mac.

Any advice?

Thanks in advance.

**Comment by seansfkelley** [comment]
2FA isn't supported (tracked by #7), so unfortunately that should not work.

Some debugging information, if you have it:

- In the settings page of the extension, it may have a section at the bottom labeled "Debugging". If so, can you paste that content here? (It has no identifying information in it.)
- Can you provide the exact error message you're seeing? Perhaps a screenshot?

For the computers that are working, did you set them up and log in before you enabled 2FA? It's possible they're hanging onto a successfully logged-in session from before you enabled 2FA. Similarly, disabling 2FA to get your Mac to work might not be fixing the issue because it's also holding onto the failed session when it tried to log in with 2FA, even though 2FA is now turned off.

If this is true, you should be able to "break" your working installations by enabling 2FA, then uninstalling and reinstalling the extension. You should also be able to fix your Mac by, conversely, disabling 2FA, then uninstalling and reinstalling the extension. (The installation is just to clear the login session -- a "force re-login" button is tracked by #71.)

I don't have plans to support 2FA soon because it appears to be quite a bit of work. If the above methods allow you to successfully connect and then re-enable 2FA, that would be good to know. In that case, be warned that they are prone to start failing for the same reason in the future, because occasionally the login sessions get stale and the extension will attempt to log in again.

**Comment by 3ventHori7on** [comment]
**> In the settings page of the extension, it may have a section at the bottom labeled "Debugging".** 
I took a screenshot with my quickconnect address obscured - hope this helps.

**> For the computers that are working, did you set them up and log in before you enabled 2FA?**
No - 2FA was enabled before I installed the add-on, and I was able to log in despite this. I find it quite troubling that through the add-on I was able to circumvent 2FA. FYI both of the PCs I was able to connect to the add-on with (despite having 2FA enabled) were connected to my NAS via quickconnect and were not on the LAN.

**> You should also be able to fix your Mac by, conversely, disabling 2FA, then uninstalling and reinstalling the extension.**
Actually I realised that the reason I couldn't connect to the add-on despite disabling 2FA was that I had enforced 2FA in the Synology Control Panel under User - Advanced. I changed this setting and disabled 2FA and was able to connect to the add-on.

**> If the above methods allow you to successfully connect and then re-enable 2FA, that would be good to know.**
I have connected with the add-on and I have since gone back to my NAS and enabled 2FA. The connection seems to have been maintained despite having enabled 2FA. 

You can view the screenshots [here](https://screenshot.net/5o4ymt4) and [here](https://screenshot.net/njdp3b1).

Hope this helps - and thanks once again for the add-on.

**Comment by seansfkelley** [comment]
I agree that it's rather strange that you were able to log some computers in despite 2FA being enabled. That seems like a bug on Synology's part; that the extension normally fails to log in and reports the 2FA requirement is all that it is expected to do right now. Thank you for responding to my questions, and sorry that 2FA isn't yet supported. I'm going to close this issue in preference to #7 and newly-filed #91 since it seems like the extension is working properly. If you have other questions, feel free to reopen or file another issue!

**Comment by seansfkelley** [comment]
No. As noted in the comments above, #7 is the tracking issue.
