### ISSUE TITLE
Feature request : Youtube auto-url entry

### ISSUE THREAD

**Issue by RobAley** [seansfkelley/synology-download-manager#92]
This is a great extension. Often I want to download YouTube videos, however the right-click method doesn't work on them (at least in Firefox). So what I have to do at the moment is copy the URL from the browser address bar, open the extension, click the plus button, paste the in the url.
 
Download Station only needs the url of the webpage for youtube (and some other site) videos (not the exact video file/stream URL etc), it would be great if there were a way to cut out the copy/paste from the above. E.g. a button to add the current page url, or the page url pre-filled out in the url box, or even better a single click button that appears somewhere in the browser ui  or on the web page for certain site (or all sites) that adds the url to the download station.

I'm not sure how easy / feasible this is?

Thanks

**Comment by seansfkelley** [comment]
Since this behavior is relevant only to a very few sites, I think a button that appears on the site itself in an accessible place (such as next to the title of the video) is probably the most appropriate option. It should be and easy-moderate amount of work to do: digging around in the DOM of youtube.com to figure out where to attach the button and delivering a content script to do that that talks to the background script to add tasks. Unfortunately, I don't have time to do any non-urgent feature work on this extension at the moment.
